# Generated by Django 5.2.9 on 2025-12-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personal_info',
            table='personal_info',
        ),
    ]
