# Generated by Django 5.2.9 on 2025-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('image', models.URLField(default='https://randomuser.me/api/portraits/lego/1.jpg')),
            ],
        ),
    ]
