# Generated by Django 5.2.9 on 2025-12-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimony',
        ),
    ]
